### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by stephanlachnit** [toddr/XML-Parser#87]
Could you add a git tag for 2.46? ~In Debian we rely on git tags to notify about new versions, but that hasn't happened due to the missing tag.~ Edit: actually that is wrong, sorry. We get the version from CPAN. Feel free to close this.

**Comment by glensc** [comment]
git tags are useful anyway to check what version contains the changes.

**Comment by glensc** [comment]
2.46 tag is present now:
- https://github.com/toddr/XML-Parser/releases/tag/2.46
