### ISSUE TITLE
Pod formatting problem in XML::Parser::Style::Tree

### ISSUE THREAD

**Issue by eserte** [toddr/XML-Parser#91]
The problematic formatting can be seen here: https://metacpan.org/release/TODDR/XML-Parser-2.46/view/Parser/Style/Tree.pm#DESCRIPTION : the text starting with "Tag Content" is not formatted as a verbatim paragraph.

**Comment by toddr** [comment]
I agree with you but I don't see a bug in the file. Not sure if this is a metacpan problem.

**Comment by toddr** [comment]
This was fixed in #91 I think. Should be in the next release.
